// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _GetPublicJobEp } from '../src/api/getPublicJob';
import type { default as _ListPublicJobsEp } from '../src/api/listPublicJobs';
import type { default as _SubmitApplicationEp } from '../src/api/submitApplication';

type _GetPublicJobCfg = typeof _GetPublicJobEp;
export type GetPublicJobInputType = NonNullable<_GetPublicJobCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetPublicJobCfg['execute']>[0]['input'];
export type GetPublicJobOutputType = Awaited<ReturnType<_GetPublicJobCfg['execute']>>;
export const getPublicJob = createCaller<GetPublicJobInputType, GetPublicJobOutputType>('getPublicJob');

type _ListPublicJobsCfg = typeof _ListPublicJobsEp;
export type ListPublicJobsInputType = NonNullable<_ListPublicJobsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPublicJobsCfg['execute']>[0]['input'];
export type ListPublicJobsOutputType = Awaited<ReturnType<_ListPublicJobsCfg['execute']>>;
export const listPublicJobs = createCaller<ListPublicJobsInputType, ListPublicJobsOutputType>('listPublicJobs');

type _SubmitApplicationCfg = typeof _SubmitApplicationEp;
export type SubmitApplicationInputType = NonNullable<_SubmitApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitApplicationCfg['execute']>[0]['input'];
export type SubmitApplicationOutputType = Awaited<ReturnType<_SubmitApplicationCfg['execute']>>;
export const submitApplication = createCaller<SubmitApplicationInputType, SubmitApplicationOutputType>('submitApplication');


export const api = {
  getPublicJob,
  listPublicJobs,
  submitApplication,
};
