// Auto-generated by zitejs generate. Do not edit manually.

import { createCaller } from 'zitejs/caller';

import type { default as _AddNoteEp } from '../src/api/addNote';
import type { default as _AiDraftEmailEp } from '../src/api/aiDraftEmail';
import type { default as _AiParseResumeEp } from '../src/api/aiParseResume';
import type { default as _AiSummarizeCandidateEp } from '../src/api/aiSummarizeCandidate';
import type { default as _BootstrapEp } from '../src/api/bootstrap';
import type { default as _BulkUpdateApplicationsEp } from '../src/api/bulkUpdateApplications';
import type { default as _CreateCandidateEp } from '../src/api/createCandidate';
import type { default as _DeleteEmailTemplateEp } from '../src/api/deleteEmailTemplate';
import type { default as _GetAnalyticsEp } from '../src/api/getAnalytics';
import type { default as _GetApplicationEp } from '../src/api/getApplication';
import type { default as _GetCandidateEp } from '../src/api/getCandidate';
import type { default as _GetIntegrationStatusEp } from '../src/api/getIntegrationStatus';
import type { default as _ListCandidatesEp } from '../src/api/listCandidates';
import type { default as _ListEmailTemplatesEp } from '../src/api/listEmailTemplates';
import type { default as _ListInterviewsEp } from '../src/api/listInterviews';
import type { default as _ListMyWorkEp } from '../src/api/listMyWork';
import type { default as _ListPipelineEp } from '../src/api/listPipeline';
import type { default as _MoveApplicationEp } from '../src/api/moveApplication';
import type { default as _RemoveTeamMemberEp } from '../src/api/removeTeamMember';
import type { default as _SeedDemoDataEp } from '../src/api/seedDemoData';
import type { default as _SendCandidateEmailEp } from '../src/api/sendCandidateEmail';
import type { default as _SubmitScorecardEp } from '../src/api/submitScorecard';
import type { default as _UpdateApplicationEp } from '../src/api/updateApplication';
import type { default as _UpdateCandidateEp } from '../src/api/updateCandidate';
import type { default as _UpsertEmailTemplateEp } from '../src/api/upsertEmailTemplate';
import type { default as _UpsertInterviewEp } from '../src/api/upsertInterview';
import type { default as _UpsertJobEp } from '../src/api/upsertJob';
import type { default as _UpsertOfferEp } from '../src/api/upsertOffer';
import type { default as _UpsertStagesEp } from '../src/api/upsertStages';
import type { default as _UpsertTeamMemberEp } from '../src/api/upsertTeamMember';

type _AddNoteCfg = typeof _AddNoteEp;
export type AddNoteInputType = NonNullable<_AddNoteCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AddNoteCfg['execute']>[0]['input'];
export type AddNoteOutputType = Awaited<ReturnType<_AddNoteCfg['execute']>>;
export const addNote = createCaller<AddNoteInputType, AddNoteOutputType>('addNote');

type _AiDraftEmailCfg = typeof _AiDraftEmailEp;
export type AiDraftEmailInputType = NonNullable<_AiDraftEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiDraftEmailCfg['execute']>[0]['input'];
export type AiDraftEmailOutputType = Awaited<ReturnType<_AiDraftEmailCfg['execute']>>;
export const aiDraftEmail = createCaller<AiDraftEmailInputType, AiDraftEmailOutputType>('aiDraftEmail');

type _AiParseResumeCfg = typeof _AiParseResumeEp;
export type AiParseResumeInputType = NonNullable<_AiParseResumeCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiParseResumeCfg['execute']>[0]['input'];
export type AiParseResumeOutputType = Awaited<ReturnType<_AiParseResumeCfg['execute']>>;
export const aiParseResume = createCaller<AiParseResumeInputType, AiParseResumeOutputType>('aiParseResume');

type _AiSummarizeCandidateCfg = typeof _AiSummarizeCandidateEp;
export type AiSummarizeCandidateInputType = NonNullable<_AiSummarizeCandidateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_AiSummarizeCandidateCfg['execute']>[0]['input'];
export type AiSummarizeCandidateOutputType = Awaited<ReturnType<_AiSummarizeCandidateCfg['execute']>>;
export const aiSummarizeCandidate = createCaller<AiSummarizeCandidateInputType, AiSummarizeCandidateOutputType>('aiSummarizeCandidate');

type _BootstrapCfg = typeof _BootstrapEp;
export type BootstrapInputType = NonNullable<_BootstrapCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BootstrapCfg['execute']>[0]['input'];
export type BootstrapOutputType = Awaited<ReturnType<_BootstrapCfg['execute']>>;
export const bootstrap = createCaller<BootstrapInputType, BootstrapOutputType>('bootstrap');

type _BulkUpdateApplicationsCfg = typeof _BulkUpdateApplicationsEp;
export type BulkUpdateApplicationsInputType = NonNullable<_BulkUpdateApplicationsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_BulkUpdateApplicationsCfg['execute']>[0]['input'];
export type BulkUpdateApplicationsOutputType = Awaited<ReturnType<_BulkUpdateApplicationsCfg['execute']>>;
export const bulkUpdateApplications = createCaller<BulkUpdateApplicationsInputType, BulkUpdateApplicationsOutputType>('bulkUpdateApplications');

type _CreateCandidateCfg = typeof _CreateCandidateEp;
export type CreateCandidateInputType = NonNullable<_CreateCandidateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_CreateCandidateCfg['execute']>[0]['input'];
export type CreateCandidateOutputType = Awaited<ReturnType<_CreateCandidateCfg['execute']>>;
export const createCandidate = createCaller<CreateCandidateInputType, CreateCandidateOutputType>('createCandidate');

type _DeleteEmailTemplateCfg = typeof _DeleteEmailTemplateEp;
export type DeleteEmailTemplateInputType = NonNullable<_DeleteEmailTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_DeleteEmailTemplateCfg['execute']>[0]['input'];
export type DeleteEmailTemplateOutputType = Awaited<ReturnType<_DeleteEmailTemplateCfg['execute']>>;
export const deleteEmailTemplate = createCaller<DeleteEmailTemplateInputType, DeleteEmailTemplateOutputType>('deleteEmailTemplate');

type _GetAnalyticsCfg = typeof _GetAnalyticsEp;
export type GetAnalyticsInputType = NonNullable<_GetAnalyticsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetAnalyticsCfg['execute']>[0]['input'];
export type GetAnalyticsOutputType = Awaited<ReturnType<_GetAnalyticsCfg['execute']>>;
export const getAnalytics = createCaller<GetAnalyticsInputType, GetAnalyticsOutputType>('getAnalytics');

type _GetApplicationCfg = typeof _GetApplicationEp;
export type GetApplicationInputType = NonNullable<_GetApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetApplicationCfg['execute']>[0]['input'];
export type GetApplicationOutputType = Awaited<ReturnType<_GetApplicationCfg['execute']>>;
export const getApplication = createCaller<GetApplicationInputType, GetApplicationOutputType>('getApplication');

type _GetCandidateCfg = typeof _GetCandidateEp;
export type GetCandidateInputType = NonNullable<_GetCandidateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetCandidateCfg['execute']>[0]['input'];
export type GetCandidateOutputType = Awaited<ReturnType<_GetCandidateCfg['execute']>>;
export const getCandidate = createCaller<GetCandidateInputType, GetCandidateOutputType>('getCandidate');

type _GetIntegrationStatusCfg = typeof _GetIntegrationStatusEp;
export type GetIntegrationStatusInputType = NonNullable<_GetIntegrationStatusCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_GetIntegrationStatusCfg['execute']>[0]['input'];
export type GetIntegrationStatusOutputType = Awaited<ReturnType<_GetIntegrationStatusCfg['execute']>>;
export const getIntegrationStatus = createCaller<GetIntegrationStatusInputType, GetIntegrationStatusOutputType>('getIntegrationStatus');

type _ListCandidatesCfg = typeof _ListCandidatesEp;
export type ListCandidatesInputType = NonNullable<_ListCandidatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListCandidatesCfg['execute']>[0]['input'];
export type ListCandidatesOutputType = Awaited<ReturnType<_ListCandidatesCfg['execute']>>;
export const listCandidates = createCaller<ListCandidatesInputType, ListCandidatesOutputType>('listCandidates');

type _ListEmailTemplatesCfg = typeof _ListEmailTemplatesEp;
export type ListEmailTemplatesInputType = NonNullable<_ListEmailTemplatesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListEmailTemplatesCfg['execute']>[0]['input'];
export type ListEmailTemplatesOutputType = Awaited<ReturnType<_ListEmailTemplatesCfg['execute']>>;
export const listEmailTemplates = createCaller<ListEmailTemplatesInputType, ListEmailTemplatesOutputType>('listEmailTemplates');

type _ListInterviewsCfg = typeof _ListInterviewsEp;
export type ListInterviewsInputType = NonNullable<_ListInterviewsCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListInterviewsCfg['execute']>[0]['input'];
export type ListInterviewsOutputType = Awaited<ReturnType<_ListInterviewsCfg['execute']>>;
export const listInterviews = createCaller<ListInterviewsInputType, ListInterviewsOutputType>('listInterviews');

type _ListMyWorkCfg = typeof _ListMyWorkEp;
export type ListMyWorkInputType = NonNullable<_ListMyWorkCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListMyWorkCfg['execute']>[0]['input'];
export type ListMyWorkOutputType = Awaited<ReturnType<_ListMyWorkCfg['execute']>>;
export const listMyWork = createCaller<ListMyWorkInputType, ListMyWorkOutputType>('listMyWork');

type _ListPipelineCfg = typeof _ListPipelineEp;
export type ListPipelineInputType = NonNullable<_ListPipelineCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_ListPipelineCfg['execute']>[0]['input'];
export type ListPipelineOutputType = Awaited<ReturnType<_ListPipelineCfg['execute']>>;
export const listPipeline = createCaller<ListPipelineInputType, ListPipelineOutputType>('listPipeline');

type _MoveApplicationCfg = typeof _MoveApplicationEp;
export type MoveApplicationInputType = NonNullable<_MoveApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_MoveApplicationCfg['execute']>[0]['input'];
export type MoveApplicationOutputType = Awaited<ReturnType<_MoveApplicationCfg['execute']>>;
export const moveApplication = createCaller<MoveApplicationInputType, MoveApplicationOutputType>('moveApplication');

type _RemoveTeamMemberCfg = typeof _RemoveTeamMemberEp;
export type RemoveTeamMemberInputType = NonNullable<_RemoveTeamMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_RemoveTeamMemberCfg['execute']>[0]['input'];
export type RemoveTeamMemberOutputType = Awaited<ReturnType<_RemoveTeamMemberCfg['execute']>>;
export const removeTeamMember = createCaller<RemoveTeamMemberInputType, RemoveTeamMemberOutputType>('removeTeamMember');

type _SeedDemoDataCfg = typeof _SeedDemoDataEp;
export type SeedDemoDataInputType = NonNullable<_SeedDemoDataCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SeedDemoDataCfg['execute']>[0]['input'];
export type SeedDemoDataOutputType = Awaited<ReturnType<_SeedDemoDataCfg['execute']>>;
export const seedDemoData = createCaller<SeedDemoDataInputType, SeedDemoDataOutputType>('seedDemoData');

type _SendCandidateEmailCfg = typeof _SendCandidateEmailEp;
export type SendCandidateEmailInputType = NonNullable<_SendCandidateEmailCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SendCandidateEmailCfg['execute']>[0]['input'];
export type SendCandidateEmailOutputType = Awaited<ReturnType<_SendCandidateEmailCfg['execute']>>;
export const sendCandidateEmail = createCaller<SendCandidateEmailInputType, SendCandidateEmailOutputType>('sendCandidateEmail');

type _SubmitScorecardCfg = typeof _SubmitScorecardEp;
export type SubmitScorecardInputType = NonNullable<_SubmitScorecardCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_SubmitScorecardCfg['execute']>[0]['input'];
export type SubmitScorecardOutputType = Awaited<ReturnType<_SubmitScorecardCfg['execute']>>;
export const submitScorecard = createCaller<SubmitScorecardInputType, SubmitScorecardOutputType>('submitScorecard');

type _UpdateApplicationCfg = typeof _UpdateApplicationEp;
export type UpdateApplicationInputType = NonNullable<_UpdateApplicationCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateApplicationCfg['execute']>[0]['input'];
export type UpdateApplicationOutputType = Awaited<ReturnType<_UpdateApplicationCfg['execute']>>;
export const updateApplication = createCaller<UpdateApplicationInputType, UpdateApplicationOutputType>('updateApplication');

type _UpdateCandidateCfg = typeof _UpdateCandidateEp;
export type UpdateCandidateInputType = NonNullable<_UpdateCandidateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpdateCandidateCfg['execute']>[0]['input'];
export type UpdateCandidateOutputType = Awaited<ReturnType<_UpdateCandidateCfg['execute']>>;
export const updateCandidate = createCaller<UpdateCandidateInputType, UpdateCandidateOutputType>('updateCandidate');

type _UpsertEmailTemplateCfg = typeof _UpsertEmailTemplateEp;
export type UpsertEmailTemplateInputType = NonNullable<_UpsertEmailTemplateCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertEmailTemplateCfg['execute']>[0]['input'];
export type UpsertEmailTemplateOutputType = Awaited<ReturnType<_UpsertEmailTemplateCfg['execute']>>;
export const upsertEmailTemplate = createCaller<UpsertEmailTemplateInputType, UpsertEmailTemplateOutputType>('upsertEmailTemplate');

type _UpsertInterviewCfg = typeof _UpsertInterviewEp;
export type UpsertInterviewInputType = NonNullable<_UpsertInterviewCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertInterviewCfg['execute']>[0]['input'];
export type UpsertInterviewOutputType = Awaited<ReturnType<_UpsertInterviewCfg['execute']>>;
export const upsertInterview = createCaller<UpsertInterviewInputType, UpsertInterviewOutputType>('upsertInterview');

type _UpsertJobCfg = typeof _UpsertJobEp;
export type UpsertJobInputType = NonNullable<_UpsertJobCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertJobCfg['execute']>[0]['input'];
export type UpsertJobOutputType = Awaited<ReturnType<_UpsertJobCfg['execute']>>;
export const upsertJob = createCaller<UpsertJobInputType, UpsertJobOutputType>('upsertJob');

type _UpsertOfferCfg = typeof _UpsertOfferEp;
export type UpsertOfferInputType = NonNullable<_UpsertOfferCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertOfferCfg['execute']>[0]['input'];
export type UpsertOfferOutputType = Awaited<ReturnType<_UpsertOfferCfg['execute']>>;
export const upsertOffer = createCaller<UpsertOfferInputType, UpsertOfferOutputType>('upsertOffer');

type _UpsertStagesCfg = typeof _UpsertStagesEp;
export type UpsertStagesInputType = NonNullable<_UpsertStagesCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertStagesCfg['execute']>[0]['input'];
export type UpsertStagesOutputType = Awaited<ReturnType<_UpsertStagesCfg['execute']>>;
export const upsertStages = createCaller<UpsertStagesInputType, UpsertStagesOutputType>('upsertStages');

type _UpsertTeamMemberCfg = typeof _UpsertTeamMemberEp;
export type UpsertTeamMemberInputType = NonNullable<_UpsertTeamMemberCfg['inputSchema']> extends { _input: infer I } ? I : Parameters<_UpsertTeamMemberCfg['execute']>[0]['input'];
export type UpsertTeamMemberOutputType = Awaited<ReturnType<_UpsertTeamMemberCfg['execute']>>;
export const upsertTeamMember = createCaller<UpsertTeamMemberInputType, UpsertTeamMemberOutputType>('upsertTeamMember');


export const api = {
  addNote,
  aiDraftEmail,
  aiParseResume,
  aiSummarizeCandidate,
  bootstrap,
  bulkUpdateApplications,
  createCandidate,
  deleteEmailTemplate,
  getAnalytics,
  getApplication,
  getCandidate,
  getIntegrationStatus,
  listCandidates,
  listEmailTemplates,
  listInterviews,
  listMyWork,
  listPipeline,
  moveApplication,
  removeTeamMember,
  seedDemoData,
  sendCandidateEmail,
  submitScorecard,
  updateApplication,
  updateCandidate,
  upsertEmailTemplate,
  upsertInterview,
  upsertJob,
  upsertOffer,
  upsertStages,
  upsertTeamMember,
};
