// Auto-generated by zitejs generate. Do not edit manually.
//
// Usage in endpoint files (src/api/*.ts):
//   import { zite } from "zitejs/db";
//
// Always use "zitejs/db" — never use relative paths like "../../.zite/db".
// The tsconfig aliases resolve zitejs/* imports to the correct .zite/ files.
//
// Table client methods (all take a single params object):
//   .findAll({ filters?, sort?, offset?, limit?, fields? }) → { records: T[], hasMore: boolean }
//     filters: { fieldName: value } for equality, or { fieldName: { <op>: value } }
//     operators: contains, not, in, notIn, lt, lte, gt, gte
//       `not: null` means "is set". An empty `in: []` matches nothing; an
//       empty `notIn: []` applies no filter.
//     sort is currently IGNORED here — it is stripped before the request.
//       (it does work on zite.auth.findAllUsers). Order in SQL instead.
//     limit defaults to 500, max 2000; offset is a row count (a number)
//     a filter value of `undefined` is REJECTED (it would query unfiltered
//       and match an arbitrary record). Check the value first.
//   .findOne({ id?, filters?, fields? }) → T | undefined
//   .create({ record }) → T
//   .update({ id, record }) → { id: string, fields: Partial<T> }
//   .delete({ id }) → { success: true, id: string }
//   .bulkCreate({ records, matchOn? }) → { success: boolean, records: T[] }
//     up to 100 records per call; matchOn upserts on those fields
//
// Reading these types:
//   SDK names are stable identifiers — they do NOT change when a table or field is
//   renamed. Each carries its current user-facing name in quotes (// "Task Name").
//   Where the two differ the field was renamed, and the quoted name is what it means
//   now — treat it as the source of truth.
//   Values are RAW: dates are ISO strings, durations are seconds. Format them for
//   display yourself, following the display config in each field's comment.
//   PERCENT fields are stored as decimals — 0.5 is 50%, 1.0 is 100%.
//   LINKED RECORD fields hold UUID record ids from findOne/findAll — never invent one.
//   Computed and system-managed fields (formula, rollup, lookup, autonumber,
//   created/updated timestamps and more) are absent from the *Input types —
//   a write to one is rejected or silently dropped.
//
// Zite auth users:
//   zite.auth.findAllUsers({ appIds?, filter?, filters?, sort?, limit?, offset? })
//     Supports the same filter, sort, and pagination options as table .findAll()
//     appIds restricts results to users belonging to any listed app
//   zite.auth.updateUserProfile(userId, { firstName?, lastName?, image? })
//   User email addresses cannot be updated through this API
//
// Raw SQL (read-only SELECTs for aggregates, joins, multi-table queries):
//   zite.sql({ query: "SELECT ...", params?: [...] })
//     → { rows: Record<string, unknown>[], columns, rowCount, truncated }
//     Capped at 2000 rows — `truncated: true` means there were more, so paginate in
//     SQL rather than assuming you got everything. Queries time out after 10s.
//     columns[].name is the SDK name; columns[].originalName is the underlying
//     database column (or your own SQL alias).
//
// SQL guidelines:
//   - Use SDK names for tables (PascalCase) and fields (camelCase)
//   - ALWAYS double-quote every identifier: FROM "Orders", WHERE "status" = $1
//   - Use params array for user input ($1, $2, ...): never interpolate into SQL
//   - Auth users are available as "ziteUsers" with id, name, email, firstName, lastName, and image
//   - Soft-deleted rows are excluded automatically — no WHERE deleted_at IS NULL
//   - SELECT only — use .create/.update/.delete for writes
//   - Load the "zite:sql" skill for full SQL reference (formulas, lookups, etc.)
//
// Link tables for zite.sql() JOINs (use these exact names):
//   "JobsTeamMembers" — columns: "jobsId", "teamMembersId" (joins "Jobs" and "Team Members")
//   "JobsStages" — columns: "jobsId", "stagesId" (joins "Jobs" and "Stages")
//   "ApplicationsCandidates" — columns: "applicationsId", "candidatesId" (joins "Applications" and "Candidates")
//   "ApplicationsJobs" — columns: "applicationsId", "jobsId" (joins "Applications" and "Jobs")
//   "ApplicationsStages" — columns: "applicationsId", "stagesId" (joins "Applications" and "Stages")
//   "ApplicationsTeamMembers" — columns: "applicationsId", "teamMembersId" (joins "Applications" and "Team Members")
//   "ApplicationsInterviews" — columns: "applicationsId", "interviewsId" (joins "Applications" and "Interviews")
//   "InterviewsStages" — columns: "interviewsId", "stagesId" (joins "Interviews" and "Stages")
//   "InterviewsTeamMembers" — columns: "interviewsId", "teamMembersId" (joins "Interviews" and "Team Members")
//   "InterviewsScorecards" — columns: "interviewsId", "scorecardsId" (joins "Interviews" and "Scorecards")
//   "ApplicationsScorecards" — columns: "applicationsId", "scorecardsId" (joins "Applications" and "Scorecards")
//   "ScorecardsTeamMembers" — columns: "scorecardsId", "teamMembersId" (joins "Scorecards" and "Team Members")
//   "ActivitiesApplications" — columns: "activitiesId", "applicationsId" (joins "Activities" and "Applications")
//   "ActivitiesCandidates" — columns: "activitiesId", "candidatesId" (joins "Activities" and "Candidates")
//   "ActivitiesTeamMembers" — columns: "activitiesId", "teamMembersId" (joins "Activities" and "Team Members")
//   "ApplicationsOffers" — columns: "applicationsId", "offersId" (joins "Applications" and "Offers")
//   "OffersTeamMembers" — columns: "offersId", "teamMembersId" (joins "Offers" and "Team Members")
//   "ApplicationsEmailMessages" — columns: "applicationsId", "emailMessagesId" (joins "Applications" and "Email Messages")
//   "CandidatesEmailMessages" — columns: "candidatesId", "emailMessagesId" (joins "Candidates" and "Email Messages")
//   "EmailMessagesTeamMembers" — columns: "emailMessagesId", "teamMembersId" (joins "Email Messages" and "Team Members")
import { createTableClient, createSqlClient, createAuthClient } from 'zitejs/runtime';

/** An attachment as returned when reading a record. */
export type ZiteAttachment = {
  /** Original filename as uploaded. */
  filename: string;
  /** Display name — may differ from `filename`. */
  originalName: string;
  /** File size in bytes. */
  size: number;
  mimeType: string;
  /** Publicly accessible URL. */
  url: string;
  /** ISO timestamp of the upload. */
  uploadedAt: string;
  metadata?: Record<string, unknown>;
};

/** What you may write to an attachments field: a URL, a URL with a name, or an attachment you read earlier. */
export type ZiteAttachmentInput =
  | string
  | { url: string; filename?: string }
  | ZiteAttachment;

/** A record in the "Team Members" table, as it is read back. */
export type TeamMembersRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  email?: string;
  title?: string;
  avatarUrl?: string;
  role?: "Admin" | "Recruiter" | "Hiring Manager" | "Interviewer" | "Coordinator" | string;
  department?: "Engineering" | "Product" | "Design" | "Sales" | "Marketing" | "Operations" | "Finance" | "People" | string;
  active?: boolean;
  /** Links to jobs ("Jobs"). Single record only. "Jobs" */
  jobs?: string | string[];
  /** Links to jobs ("Jobs"). Single record only. "Jobs (1)" */
  jobs1?: string | string[];
  /** Links to applications ("Applications"). Single record only. "Applications" */
  applications?: string | string[];
  /** Links to interviews ("Interviews"). "Interviews" */
  interviews?: string | string[];
  /** Links to scorecards ("Scorecards"). Single record only. "Scorecards" */
  scorecards?: string | string[];
  /** Links to activities ("Activities"). Single record only. "Activities" */
  activities?: string | string[];
  /** Links to offers ("Offers"). Single record only. "Offers" */
  offers?: string | string[];
  /** Links to emailMessages ("Email Messages"). Single record only. "Email Messages" */
  emailMessages?: string | string[];
};

/** What you may write when creating or updating a record in the "Team Members" table. */
export type TeamMembersRecordInput = {
  name: string | null;
  email: string | null;
  title: string | null;
  avatarUrl: string | null;
  role: "Admin" | "Recruiter" | "Hiring Manager" | "Interviewer" | "Coordinator" | string | null;
  department: "Engineering" | "Product" | "Design" | "Sales" | "Marketing" | "Operations" | "Finance" | "People" | string | null;
  active: string | boolean | null;
  jobs: string | string[] | null;
  jobs1: string | string[] | null;
  applications: string | string[] | null;
  interviews: string | string[] | null;
  scorecards: string | string[] | null;
  activities: string | string[] | null;
  offers: string | string[] | null;
  emailMessages: string | string[] | null;
};

/** A record in the "Candidates" table, as it is read back. */
export type CandidatesRecordType = {
  id: string;
  /** Primary field. "Full Name" */
  fullName?: string;
  email?: string;
  phone?: string;
  headline?: string;
  currentCompany?: string;
  location?: string;
  linkedInUrl?: string;
  gitHubUrl?: string;
  portfolioUrl?: string;
  avatarUrl?: string;
  /** "Years Experience". 0 decimal places, format: local (e.g. 1,000,000.50) */
  yearsExperience?: number;
  resume?: ZiteAttachment[];
  aiSummary?: string;
  source?: "Applied" | "Referral" | "Sourced" | "Agency" | "Event" | "Inbound" | string;
  sourceDetail?: string;
  skills?: ("TypeScript" | "React" | "Python" | "Go" | "Rust" | "Kubernetes" | "AWS" | "Postgres" | "Machine Learning" | "Product Strategy" | "Figma" | "Design Systems" | "User Research" | "Enterprise Sales" | "Demand Gen" | "Analytics" | string)[];
  tags?: ("Top Prospect" | "Referral" | "Silver Medalist" | "Needs Visa" | "Senior" | "Re-engage Later" | string)[];
  /** Links to applications ("Applications"). Single record only. "Applications" */
  applications?: string | string[];
  /** Links to activities ("Activities"). Single record only. "Activities" */
  activities?: string | string[];
  /** Links to emailMessages ("Email Messages"). Single record only. "Email Messages" */
  emailMessages?: string | string[];
};

/** What you may write when creating or updating a record in the "Candidates" table. */
export type CandidatesRecordInput = {
  fullName: string | null;
  email: string | null;
  phone: string | null;
  headline: string | null;
  currentCompany: string | null;
  location: string | null;
  linkedInUrl: string | null;
  gitHubUrl: string | null;
  portfolioUrl: string | null;
  avatarUrl: string | null;
  yearsExperience: string | number | null;
  resume: ZiteAttachmentInput[] | ZiteAttachmentInput | null;
  aiSummary: string | null;
  source: "Applied" | "Referral" | "Sourced" | "Agency" | "Event" | "Inbound" | string | null;
  sourceDetail: string | null;
  skills: "TypeScript" | "React" | "Python" | "Go" | "Rust" | "Kubernetes" | "AWS" | "Postgres" | "Machine Learning" | "Product Strategy" | "Figma" | "Design Systems" | "User Research" | "Enterprise Sales" | "Demand Gen" | "Analytics" | string | ("TypeScript" | "React" | "Python" | "Go" | "Rust" | "Kubernetes" | "AWS" | "Postgres" | "Machine Learning" | "Product Strategy" | "Figma" | "Design Systems" | "User Research" | "Enterprise Sales" | "Demand Gen" | "Analytics" | string)[] | null;
  tags: "Top Prospect" | "Referral" | "Silver Medalist" | "Needs Visa" | "Senior" | "Re-engage Later" | string | ("Top Prospect" | "Referral" | "Silver Medalist" | "Needs Visa" | "Senior" | "Re-engage Later" | string)[] | null;
  applications: string | string[] | null;
  activities: string | string[] | null;
  emailMessages: string | string[] | null;
};

/** A record in the "Email Templates" table, as it is read back. */
export type EmailTemplatesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  subject?: string;
  body?: string;
  category?: "Outreach" | "Screening" | "Scheduling" | "Rejection" | "Offer" | "Follow-up" | string;
};

/** What you may write when creating or updating a record in the "Email Templates" table. */
export type EmailTemplatesRecordInput = {
  name: string | null;
  subject: string | null;
  body: string | null;
  category: "Outreach" | "Screening" | "Scheduling" | "Rejection" | "Offer" | "Follow-up" | string | null;
};

/** A record in the "Jobs" table, as it is read back. */
export type JobsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  slug?: string;
  team?: string;
  location?: string;
  description?: string;
  requirements?: string;
  benefits?: string;
  /** "Opened Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  openedDate?: string;
  /** "Target Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  targetStartDate?: string;
  /** "Openings". 0 decimal places, format: local (e.g. 1,000,000.50) */
  openings?: number;
  /** "Salary Min". Value is a raw number; display as currency with symbol "$", 0 decimal places, format: local (e.g. 1,000,000.50) */
  salaryMin?: number;
  /** "Salary Max". Value is a raw number; display as currency with symbol "$", 0 decimal places, format: local (e.g. 1,000,000.50) */
  salaryMax?: number;
  department?: "Engineering" | "Product" | "Design" | "Sales" | "Marketing" | "Operations" | "Finance" | "People" | string;
  workplaceType?: "Remote" | "Hybrid" | "On-site" | string;
  employmentType?: "Full-time" | "Part-time" | "Contract" | "Internship" | string;
  status?: "Draft" | "Open" | "Paused" | "Closed" | "Filled" | string;
  priority?: "Low" | "Medium" | "High" | "Critical" | string;
  published?: boolean;
  confidential?: boolean;
  /** Links to teamMembers ("Team Members"). Single record only. "Hiring Manager" */
  hiringManager?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Recruiter" */
  recruiter?: string | string[];
  /** Links to stages ("Stages"). Single record only. "Stages" */
  stages?: string | string[];
  /** Links to applications ("Applications"). Single record only. "Applications" */
  applications?: string | string[];
};

/** What you may write when creating or updating a record in the "Jobs" table. */
export type JobsRecordInput = {
  title: string | null;
  slug: string | null;
  team: string | null;
  location: string | null;
  description: string | null;
  requirements: string | null;
  benefits: string | null;
  openedDate: string | Date | null;
  targetStartDate: string | Date | null;
  openings: string | number | null;
  salaryMin: string | number | null;
  salaryMax: string | number | null;
  department: "Engineering" | "Product" | "Design" | "Sales" | "Marketing" | "Operations" | "Finance" | "People" | string | null;
  workplaceType: "Remote" | "Hybrid" | "On-site" | string | null;
  employmentType: "Full-time" | "Part-time" | "Contract" | "Internship" | string | null;
  status: "Draft" | "Open" | "Paused" | "Closed" | "Filled" | string | null;
  priority: "Low" | "Medium" | "High" | "Critical" | string | null;
  published: string | boolean | null;
  confidential: string | boolean | null;
  hiringManager: string | string[] | null;
  recruiter: string | string[] | null;
  stages: string | string[] | null;
  applications: string | string[] | null;
};

/** A record in the "Stages" table, as it is read back. */
export type StagesRecordType = {
  id: string;
  /** Primary field. "Name" */
  name?: string;
  /** "Order". 0 decimal places, format: local (e.g. 1,000,000.50) */
  order?: number;
  interviewKit?: string;
  /** "Target Days". 0 decimal places, format: local (e.g. 1,000,000.50) */
  targetDays?: number;
  kind?: "Lead" | "Applied" | "Screen" | "Interview" | "Offer" | "Hired" | "Rejected" | string;
  /** Links to jobs ("Jobs"). Single record only. "Job" */
  job?: string | string[];
  /** Links to applications ("Applications"). Single record only. "Applications" */
  applications?: string | string[];
  /** Links to interviews ("Interviews"). Single record only. "Interviews" */
  interviews?: string | string[];
};

/** What you may write when creating or updating a record in the "Stages" table. */
export type StagesRecordInput = {
  name: string | null;
  order: string | number | null;
  interviewKit: string | null;
  targetDays: string | number | null;
  kind: "Lead" | "Applied" | "Screen" | "Interview" | "Offer" | "Hired" | "Rejected" | string | null;
  job: string | string[] | null;
  applications: string | string[] | null;
  interviews: string | string[] | null;
};

/** A record in the "Applications" table, as it is read back. */
export type ApplicationsRecordType = {
  id: string;
  /** Primary field. "Application" */
  application?: string;
  /** "Applied Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  appliedDate?: string;
  /** "Stage Entered At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  stageEnteredAt?: string;
  /** "Rejected Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  rejectedDate?: string;
  status?: "Active" | "Hired" | "Rejected" | "Withdrawn" | "On Hold" | string;
  /** "Rating". Max rating: 4 */
  rating?: number;
  source?: "Applied" | "Referral" | "Sourced" | "Agency" | "Event" | "Inbound" | string;
  rejectionReason?: "Lacking Experience" | "Skills Mismatch" | "Compensation" | "Location" | "Culture Fit" | "Accepted Other Offer" | "Unresponsive" | "Role Closed" | "Other" | string;
  /** Links to candidates ("Candidates"). Single record only. "Candidate" */
  candidate?: string | string[];
  /** Links to jobs ("Jobs"). Single record only. "Job" */
  job?: string | string[];
  /** Links to stages ("Stages"). Single record only. "Current Stage" */
  currentStage?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Owner" */
  owner?: string | string[];
  /** Links to interviews ("Interviews"). Single record only. "Interviews" */
  interviews?: string | string[];
  /** Links to scorecards ("Scorecards"). Single record only. "Scorecards" */
  scorecards?: string | string[];
  /** Links to activities ("Activities"). Single record only. "Activities" */
  activities?: string | string[];
  /** Links to offers ("Offers"). Single record only. "Offers" */
  offers?: string | string[];
  /** Links to emailMessages ("Email Messages"). Single record only. "Email Messages" */
  emailMessages?: string | string[];
};

/** What you may write when creating or updating a record in the "Applications" table. */
export type ApplicationsRecordInput = {
  application: string | null;
  appliedDate: string | Date | null;
  stageEnteredAt: string | Date | null;
  rejectedDate: string | Date | null;
  status: "Active" | "Hired" | "Rejected" | "Withdrawn" | "On Hold" | string | null;
  rating: string | number | null;
  source: "Applied" | "Referral" | "Sourced" | "Agency" | "Event" | "Inbound" | string | null;
  rejectionReason: "Lacking Experience" | "Skills Mismatch" | "Compensation" | "Location" | "Culture Fit" | "Accepted Other Offer" | "Unresponsive" | "Role Closed" | "Other" | string | null;
  candidate: string | string[] | null;
  job: string | string[] | null;
  currentStage: string | string[] | null;
  owner: string | string[] | null;
  interviews: string | string[] | null;
  scorecards: string | string[] | null;
  activities: string | string[] | null;
  offers: string | string[] | null;
  emailMessages: string | string[] | null;
};

/** A record in the "Interviews" table, as it is read back. */
export type InterviewsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  /** "Scheduled At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  scheduledAt?: string;
  /** "Duration Minutes". 0 decimal places, format: local (e.g. 1,000,000.50) */
  durationMinutes?: number;
  meetingLink?: string;
  location?: string;
  notes?: string;
  type?: "Phone Screen" | "Recruiter Screen" | "Technical" | "System Design" | "Behavioral" | "Hiring Manager" | "Onsite" | "Culture" | "Final" | string;
  status?: "Unscheduled" | "Scheduled" | "Completed" | "Cancelled" | "No Show" | string;
  /** Links to applications ("Applications"). Single record only. "Application" */
  application?: string | string[];
  /** Links to stages ("Stages"). Single record only. "Stage" */
  stage?: string | string[];
  /** Links to teamMembers ("Team Members"). "Interviewers" */
  interviewers?: string | string[];
  /** Links to scorecards ("Scorecards"). Single record only. "Scorecards" */
  scorecards?: string | string[];
};

/** What you may write when creating or updating a record in the "Interviews" table. */
export type InterviewsRecordInput = {
  title: string | null;
  scheduledAt: string | Date | null;
  durationMinutes: string | number | null;
  meetingLink: string | null;
  location: string | null;
  notes: string | null;
  type: "Phone Screen" | "Recruiter Screen" | "Technical" | "System Design" | "Behavioral" | "Hiring Manager" | "Onsite" | "Culture" | "Final" | string | null;
  status: "Unscheduled" | "Scheduled" | "Completed" | "Cancelled" | "No Show" | string | null;
  application: string | string[] | null;
  stage: string | string[] | null;
  interviewers: string | string[] | null;
  scorecards: string | string[] | null;
};

/** A record in the "Scorecards" table, as it is read back. */
export type ScorecardsRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  /** "Submitted At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  submittedAt?: string;
  strengths?: string;
  concerns?: string;
  notes?: string;
  /** "Overall Rating". Max rating: 4 */
  overallRating?: number;
  /** "Technical Skill". Max rating: 4 */
  technicalSkill?: number;
  /** "Communication". Max rating: 4 */
  communication?: number;
  /** "Problem Solving". Max rating: 4 */
  problemSolving?: number;
  /** "Culture Add". Max rating: 4 */
  cultureAdd?: number;
  recommendation?: "Strong Yes" | "Yes" | "No" | "Strong No" | string;
  status?: "Pending" | "Submitted" | string;
  /** Links to interviews ("Interviews"). Single record only. "Interview" */
  interview?: string | string[];
  /** Links to applications ("Applications"). Single record only. "Application" */
  application?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Interviewer" */
  interviewer?: string | string[];
};

/** What you may write when creating or updating a record in the "Scorecards" table. */
export type ScorecardsRecordInput = {
  title: string | null;
  submittedAt: string | Date | null;
  strengths: string | null;
  concerns: string | null;
  notes: string | null;
  overallRating: string | number | null;
  technicalSkill: string | number | null;
  communication: string | number | null;
  problemSolving: string | number | null;
  cultureAdd: string | number | null;
  recommendation: "Strong Yes" | "Yes" | "No" | "Strong No" | string | null;
  status: "Pending" | "Submitted" | string | null;
  interview: string | string[] | null;
  application: string | string[] | null;
  interviewer: string | string[] | null;
};

/** A record in the "Activities" table, as it is read back. */
export type ActivitiesRecordType = {
  id: string;
  /** Primary field. "Summary" */
  summary?: string;
  body?: string;
  /** "Occurred At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  occurredAt?: string;
  type?: "Note" | "Stage Change" | "Email" | "Interview Scheduled" | "Scorecard" | "Application Created" | "Status Change" | "Offer" | "Rating" | string;
  /** Links to applications ("Applications"). Single record only. "Application" */
  application?: string | string[];
  /** Links to candidates ("Candidates"). Single record only. "Candidate" */
  candidate?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Author" */
  author?: string | string[];
};

/** What you may write when creating or updating a record in the "Activities" table. */
export type ActivitiesRecordInput = {
  summary: string | null;
  body: string | null;
  occurredAt: string | Date | null;
  type: "Note" | "Stage Change" | "Email" | "Interview Scheduled" | "Scorecard" | "Application Created" | "Status Change" | "Offer" | "Rating" | string | null;
  application: string | string[] | null;
  candidate: string | string[] | null;
  author: string | string[] | null;
};

/** A record in the "Offers" table, as it is read back. */
export type OffersRecordType = {
  id: string;
  /** Primary field. "Title" */
  title?: string;
  level?: string;
  equity?: string;
  /** "Base Salary". Value is a raw number; display as currency with symbol "$", 0 decimal places, format: local (e.g. 1,000,000.50) */
  baseSalary?: number;
  /** "Signing Bonus". Value is a raw number; display as currency with symbol "$", 0 decimal places, format: local (e.g. 1,000,000.50) */
  signingBonus?: number;
  /** "Start Date". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  startDate?: string;
  /** "Expires At". Date-only field (YYYY-MM-DD string), null when unset, display as "local" format */
  expiresAt?: string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  /** "Responded At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  respondedAt?: string;
  notes?: string;
  status?: "Draft" | "Pending Approval" | "Approved" | "Sent" | "Accepted" | "Declined" | "Rescinded" | string;
  /** Links to applications ("Applications"). Single record only. "Application" */
  application?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Approver" */
  approver?: string | string[];
};

/** What you may write when creating or updating a record in the "Offers" table. */
export type OffersRecordInput = {
  title: string | null;
  level: string | null;
  equity: string | null;
  baseSalary: string | number | null;
  signingBonus: string | number | null;
  startDate: string | Date | null;
  expiresAt: string | Date | null;
  sentAt: string | Date | null;
  respondedAt: string | Date | null;
  notes: string | null;
  status: "Draft" | "Pending Approval" | "Approved" | "Sent" | "Accepted" | "Declined" | "Rescinded" | string | null;
  application: string | string[] | null;
  approver: string | string[] | null;
};

/** A record in the "Email Messages" table, as it is read back. */
export type EmailMessagesRecordType = {
  id: string;
  /** Primary field. "Subject" */
  subject?: string;
  threadId?: string;
  externalMessageId?: string;
  fromEmail?: string;
  toEmail?: string;
  body?: string;
  /** "Sent At". Date+time field (ISO 8601 timestamp), null when unset, date: "local" format, time: 12h */
  sentAt?: string;
  direction?: "Outbound" | "Inbound" | string;
  status?: "Draft" | "Sent" | "Failed" | "Logged (Not Sent)" | "Received" | string;
  /** Links to applications ("Applications"). Single record only. "Application" */
  application?: string | string[];
  /** Links to candidates ("Candidates"). Single record only. "Candidate" */
  candidate?: string | string[];
  /** Links to teamMembers ("Team Members"). Single record only. "Author" */
  author?: string | string[];
};

/** What you may write when creating or updating a record in the "Email Messages" table. */
export type EmailMessagesRecordInput = {
  subject: string | null;
  threadId: string | null;
  externalMessageId: string | null;
  fromEmail: string | null;
  toEmail: string | null;
  body: string | null;
  sentAt: string | Date | null;
  direction: "Outbound" | "Inbound" | string | null;
  status: "Draft" | "Sent" | "Failed" | "Logged (Not Sent)" | "Received" | string | null;
  application: string | string[] | null;
  candidate: string | string[] | null;
  author: string | string[] | null;
};

export interface NotificationLink {
  path?: string;
  params?: Record<string, string>;
}

export interface NotificationsCreateParams {
  recipients: string[];
  title: string;
  body?: string;
  link?: NotificationLink;
  path?: string;
  params?: Record<string, string>;
  payload?: Record<string, unknown>;
  idempotencyKey?: string;
}

export type NotificationsCreateResult =
  | { created: number }
  | { created: 0; preview: true; wouldCreate: number };

export interface ZiteAuthUser {
  id: string;
  name: string;
  email: string;
  firstName?: string;
  lastName?: string;
  image: string | null;
}

export const zite = {
  teamMembers: createTableClient<TeamMembersRecordType, TeamMembersRecordInput>('TeamMembers'), // "Team Members"
  candidates: createTableClient<CandidatesRecordType, CandidatesRecordInput>('Candidates'), // "Candidates"
  emailTemplates: createTableClient<EmailTemplatesRecordType, EmailTemplatesRecordInput>('EmailTemplates'), // "Email Templates"
  jobs: createTableClient<JobsRecordType, JobsRecordInput>('Jobs'), // "Jobs"
  stages: createTableClient<StagesRecordType, StagesRecordInput>('Stages'), // "Stages"
  applications: createTableClient<ApplicationsRecordType, ApplicationsRecordInput>('Applications'), // "Applications"
  interviews: createTableClient<InterviewsRecordType, InterviewsRecordInput>('Interviews'), // "Interviews"
  scorecards: createTableClient<ScorecardsRecordType, ScorecardsRecordInput>('Scorecards'), // "Scorecards"
  activities: createTableClient<ActivitiesRecordType, ActivitiesRecordInput>('Activities'), // "Activities"
  offers: createTableClient<OffersRecordType, OffersRecordInput>('Offers'), // "Offers"
  emailMessages: createTableClient<EmailMessagesRecordType, EmailMessagesRecordInput>('EmailMessages'), // "Email Messages"
  sql: createSqlClient(),
  auth: createAuthClient<ZiteAuthUser>(),
};
